### ISSUE TITLE
been told "Please use the Messages API instead"

### ISSUE THREAD

**Issue by GreenEric** [yrvelez/claudeR#2]
When I call the function, and try newly announced claude-3 model, comes the error message.

{"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."}} 

“”“
library(claudeR)
model = "claude-3-sonnet-20240229"
response <- claudeR(prompt = "What is the capital of France?", model = model, max_tokens = 50, 
                    api_key = Sys.getenv("Cloud_API-Key"))

cat(response)
”“”
The "claude-2" model is working for sure, BTW.
Thanks for advice.

**Comment by pqtechnican** [comment]
Same Problem here! How to get the above described solution working? With the Browser, the Claude-3 Model is working.

**Comment by yrvelez** [comment]
Thanks! Will look into this. The Claude 3 model relies on a different endpoint.

**Comment by pqtechnican** [comment]
Does anyone have the Link to the Endpoint?

**Comment by yrvelez** [comment]
Hi @pqtechnican, the endpoint is https://api.anthropic.com/v1/messages (see https://docs.anthropic.com/claude/reference/messages-examples)
