### ISSUE TITLE
Using your package (thanks!)

### ISSUE THREAD

**Issue by dylanpieper** [yrvelez/claudeR#4]
Hi,

I'm using your package in my LLM batch processing app called [batchLLM](https://github.com/dylanpieper/batchLLM). I just wanted to put my package on your radar!

Thanks for your consideration,

Dylan

**Comment by yrvelez** [comment]
That's incredible! Thank you.

**Comment by dylanpieper** [comment]
Hi Yamil,

I hope you're doing well. I’m preparing to submit my package to CRAN (first time), and since I’ve incorporated your function into it, I wanted to reach out regarding its release.

I wanted to ask for your thoughts on whether you’d prefer to release the function yourself as part of a separate package (like claudeR), which I could help you with releasing, or if you’d agree to authorship and licensing of the function within my package batchLLM. Of course, it’s entirely your decision, and I’m happy to proceed however you feel most comfortable.

Looking forward to your feedback.

Best regards,
Dylan
